config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :user
  resources :passwords, param: :token
  resources :exercises do
    member do
      delete :delete_media
    end
  end
  resources :routines do
    resources :days, only: [:create, :update, :destroy] do
      resources :blocks, only: [:create, :update, :destroy]
    end
    member do
      patch :activate
    end
  end
  get 'inertia-example', to: 'inertia_example#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "routines#active"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title inertia><%= content_for(:title) || "Bbeetle" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon-16x16.png" type="image/png" sizes="16x16">
    <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32">
    <link rel="icon" href="/favicon-96x96.png" type="image/png" sizes="96x96">
    <link rel="icon" href="/favicon-128.png" type="image/png" sizes="128x128">
    <link rel="icon" href="/favicon-196x196.png" type="image/png" sizes="196x196">
    
    <link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png" sizes="57x57">
    <link rel="apple-touch-icon" href="/apple-touch-icon-60x60.png" sizes="60x60">
    <link rel="apple-touch-icon" href="/apple-touch-icon-72x72.png" sizes="72x72">
    <link rel="apple-touch-icon" href="/apple-touch-icon-76x76.png" sizes="76x76">
    <link rel="apple-touch-icon" href="/apple-touch-icon-114x114.png" sizes="114x114">
    <link rel="apple-touch-icon" href="/apple-touch-icon-120x120.png" sizes="120x120">
    <link rel="apple-touch-icon" href="/apple-touch-icon-144x144.png" sizes="144x144">
    <link rel="apple-touch-icon" href="/apple-touch-icon-152x152.png" sizes="152x152">
    
    <meta name="msapplication-TileColor" content="#FFD700">
    <meta name="msapplication-square70x70logo" content="/mstile-70x70.png">
    <meta name="msapplication-square150x150logo" content="/mstile-150x150.png">
    <meta name="msapplication-wide310x150logo" content="/mstile-310x150.png">
    <meta name="msapplication-square310x310logo" content="/mstile-310x310.png">
    <meta name="theme-color" content="#FFD700">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= vite_stylesheet_tag "application" %>
    <%= vite_react_refresh_tag %>
    <%= vite_client_tag %>
    <%= vite_typescript_tag "inertia" %>
    <%= inertia_ssr_head %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <main class="min-h-screen h-full w-full">
      <%= yield %>
    </main>
  </body>
</html>